### PR TITLE
Custom copy method

### PR DESCRIPTION
**Pull request by fantom1**
Added support for custom copy method when the built-in rsync & cp are not flexible enough: i.e. auditing, recordkeeping, etc.

### CODE REVIEW

**Comment by gboudreau** [comment]
Thanks. I changed some of the text in the greyhole.conf, and modified the man page to include this new information, and added an example custom cp script.

**Comment by fantom1** [comment]
Thx; can you please re-build the packages? I just tried updating and the change is not there yet...

**Comment by gboudreau** [comment]
I will, as soon as you can confirm the symbolic link hack I suggested in #155 resolves the issue on Debian. I'll create a 0.9.67 version with both changes then.

**Comment by gboudreau** [comment]
0.9.67 is now available.

**Pull request merged**
