### PR TITLE
Samba 4.7 Support

### PR DESCRIPTION
**Pull request by Sparticuz**
I had to update the vfs module because of this commit: https://github.com/samba-team/samba/commit/306783d6f5d577a0b8bd31d659d8c802f22f0333, see https://github.com/Sparticuz/Greyhole/blob/samba47/samba-module/vfs_greyhole-samba-4.7%2B.c#L287-L288

- [x] 1. Create a new .patch file in `samba-module/`
- [x] 2. Create a new `samba-module/vfs_greyhole-samba-$VERSION.c`
- [x] 3. Add the new Samba version number in `build_vfs.sh @L16`
- [x] 4. Run the build_vfs.sh script
- [x] 5. Copy the resulting binaries back into your workstation
- [x] 6. Edit `INSTALL`
- [x] 7. Edit DEBIAN/Makefile
- [x] 8. Edit DEBIAN/postinst
- [x] 9. Commit all changes & new binaries

It looks like we are out of sync on some more commits to the extd_audit module. I'll submit a different PR to get us up to date with those. (Maybe just best practices, not deprecations or logic changes)

### CODE REVIEW

**Comment by gboudreau** [comment]
I can start a build for the binaries with this code? ie. the changes you talked about that you'd send in a different PR, they would be for other versions, or this one too?

**Comment by Sparticuz** [comment]
4.7 required one change on the _init function. The module works with this PR. Go ahead and start the build.

I was just looking at the history of the vfs_extd_audit from Samba, and it looks like there are some changes that we could/should pull. I'll go through them at another time.

**Comment by gboudreau** [comment]
OK, thanks.

**Comment by Sparticuz** [comment]
Thanks @gboudreau

**Pull request merged**
